[package]

name = "rust101"
version = "0.0.1"
authors = [ "vladb951" ]

[dependencies]
# reqwest = "0.9.2"
# serde = "1.0"
# serde_derive = "1.0"
# serde_json = "1.0"
# telegram-bot = "0.6"
# tokio-core = "0.1"
# futures = "0.1"